name: Web App Vercel Preview Deployment
run-name: Web App Deployment on commit ${{ github.sha }} by @${{ github.actor }}

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_WEBAPP_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_WEBAPP_PROJECT_ID }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  DIRECT_URL: ${{ secrets.DIRECT_URL }}
  BETTER_AUTH_URL: ${{ secrets.BETTER_AUTH_URL }}
  BETTER_AUTH_SECRET: ${{ secrets.BETTER_AUTH_SECRET }}
  AI_ENGINE_URL: ${{ secrets.AI_ENGINE_URL }}

on:
  workflow_run:
    workflows: ['CI - Web App']
    types: [completed]
    branches-ignore: [main]

jobs:
  deploy-preview:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web_app
    
    steps:
      - name: Checkout branch
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install Node
        uses: actions/setup-node@v6
        with:
          node-version: '22.18'
          cache: 'pnpm'
          cache-dependency-path: './web_app/pnpm-lock.yaml'

      - name: Install Vercel CLI
        run: npm install --global vercel

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      
      - name: Build Project Artifact
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifact
        run: >- 
            vercel deploy 
            -e DATABASE_URL="$DATABASE_URL"
            -e DIRECT_URL="$DIRECT_URL"
            -e BETTER_AUTH_URL="$BETTER_AUTH_URL"
            -e BETTER_AUTH_SECRET="$BETTER_AUTH_SECRET"
            -e AI_ENGINE_URL="$AI_ENGINE_URL"
            --prebuilt --token=${{ secrets.VERCEL_TOKEN }}