name: CI - Web App
run-name: CI for Web App on commit ${{ github.sha }} by @${{ github.actor }}

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  ci:
    name: Lint and Prettier Check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web_app
    steps:
      - name: Checkout branch
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install Node
        uses: actions/setup-node@v6
        with:
          node-version: '22.18'
          cache: 'pnpm'
          cache-dependency-path: './web_app/pnpm-lock.yaml'

      - name: Install deps
        run: pnpm install

      - name: Lint check
        run: pnpm lint

      - name: Prettier check
        run: pnpm format:check
