name: Deploy Web App to Vercel
run-name: Web App Deployment on commit ${{ github.sha }} by @${{ github.actor }}

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_WEBAPP_ORG_ID }}
  VERCEL_PROJECT_ID: $ {{ secrets.VERCEL_WEBAPP_PROJECT_ID }}

on:
  push:
    branches: [main]

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web_app
    
    steps:
      - name: Checkout branch
        uses: actions/checkout@v6

      - name: Install Vercel CLI
        uses: npm install --global vercel

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      
      - name: Build Project Artifact
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifact
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}